package jFrames;

import java.time.LocalDate;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;

import Codes.*;

/**
 * jModosit ablak
 * @author GFVHSO
 */
public class jModosit extends javax.swing.JFrame {
    static int sor;
    static TableModel tm;
    static String sel;
    
    /**
     * Creates new form jModosit
     * @param selectedRow kiválasztott sor indexe
     * @param model a táblázat modellje
     * @param select az adat fajtája
     */
    public jModosit(int selectedRow, TableModel model, String select) {
        sor = selectedRow;
        tm = model;
        sel = select;
        initComponents();
        initTb();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblOsztaly = new javax.swing.JLabel();
        lblAzon = new javax.swing.JLabel();
        tfOsztaly = new javax.swing.JTextField();
        tfAzon = new javax.swing.JTextField();
        lblTantargy = new javax.swing.JLabel();
        lblNev = new javax.swing.JLabel();
        lblCim = new javax.swing.JLabel();
        tfNev = new javax.swing.JTextField();
        tfCim = new javax.swing.JTextField();
        tfTantargy = new javax.swing.JTextField();
        tfIntVez = new javax.swing.JTextField();
        lblIntVez = new javax.swing.JLabel();
        btnMegse = new javax.swing.JButton();
        btnMod = new javax.swing.JButton();
        lblDatum = new javax.swing.JLabel();
        tfDatum = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Módosítás");
        setMinimumSize(new java.awt.Dimension(330, 600));

        lblOsztaly.setText("Osztály:");

        lblAzon.setText("Azonosító:");

        tfOsztaly.setEnabled(false);

        tfAzon.setEnabled(false);

        lblTantargy.setText("Tantárgy:");

        lblNev.setText("Név:");

        lblCim.setText("Cím:");

        tfNev.setEnabled(false);

        tfCim.setEnabled(false);

        tfTantargy.setEnabled(false);

        tfIntVez.setEnabled(false);

        lblIntVez.setText("Intézményvezető:");

        btnMegse.setText("Mégse");
        btnMegse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMegseActionPerformed(evt);
            }
        });

        btnMod.setText("Módosítás");
        btnMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModActionPerformed(evt);
            }
        });

        lblDatum.setText("Dátum:");

        tfDatum.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfCim)
                    .addComponent(tfNev, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnMegse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMod, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfDatum, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
                    .addComponent(tfAzon)
                    .addComponent(tfOsztaly, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tfTantargy, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tfIntVez, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNev)
                            .addComponent(lblCim)
                            .addComponent(lblDatum)
                            .addComponent(lblOsztaly)
                            .addComponent(lblAzon)
                            .addComponent(lblTantargy)
                            .addComponent(lblIntVez))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNev)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfNev, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblCim)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfCim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblDatum)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfDatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblOsztaly)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfOsztaly, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblAzon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfAzon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblTantargy)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfTantargy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblIntVez)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfIntVez, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(btnMod, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnMegse, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * A gombra kattintva a és megerősítés esetén a módosítások nem lépnek érvénybe
     * @param evt 
     */
    private void btnMegseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMegseActionPerformed
        JOptionPane opt = new JOptionPane("Biztos, hogy elveti a módosításokat?", 
                JOptionPane.QUESTION_MESSAGE, JOptionPane.YES_NO_OPTION);
        JDialog jd = opt.createDialog(opt, "Mégse");
        jd.setVisible(true);
        
        if(opt.getValue().toString().equals("0")){
            this.dispose();
        }
    }//GEN-LAST:event_btnMegseActionPerformed

    /**
     * A gomb megnyomásokar és megerősítéskor az adatok módosításra kerülnek
     * @param evt 
     */
    private void btnModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModActionPerformed
        JOptionPane opt = new JOptionPane("Biztos, hogy menti a módosításokat?", 
                JOptionPane.QUESTION_MESSAGE, JOptionPane.YES_NO_OPTION);
        JDialog jd = opt.createDialog(opt, "Módosítás");
        jd.setVisible(true);
        
        String nev = tm.getValueAt(sor, 0).toString();
        String cim = tm.getValueAt(sor, 1).toString();
        LocalDate datum = null;
        LocalDate dat = null;
        boolean ok = true;
        
        if(sel.equals("Tanár") || sel.equals("Diák"))
            datum = LocalDate.parse(tm.getValueAt(sor, 2).toString());
        
        if(opt.getValue().toString().equals("0")){
            switch (sel) {
                case "Tanár" -> {
                    if(tfNev.getText().equals("")){ //Ha üres a név mezője
                        JOptionPane.showMessageDialog(null, "Írja be a tanár nevét!", "Nem megfelelő bemenet", JOptionPane.INFORMATION_MESSAGE);
                        ok = false;
                    }
                    else if(tfCim.getText().equals("")){ //Ha üres a cím mezője
                        JOptionPane.showMessageDialog(null, "Írja be a tanár címét!", "Nem megfelelő bemenet", JOptionPane.INFORMATION_MESSAGE);
                        ok = false;
                    }
                    else if(tfDatum.getText().equals("")){ //Ha üres a dátum mezője
                        JOptionPane.showMessageDialog(null, "Írja be a tanár születési dátumát!", "Nem megfelelő bemenet", JOptionPane.INFORMATION_MESSAGE);
                        ok = false;
                    }
                    else if(!tfDatum.getText().equals("")){ //Ha nem megfelelő a dátum formátuma
                        try{
                            dat = LocalDate.parse(tfDatum.getText());
                        }
                        catch(Exception ex){
                            JOptionPane.showMessageDialog(null, "Nem megfelelő formátum!\nHelyes formátum: ÉÉÉÉ-HH-NN", "Nem megfelelő bemenet", JOptionPane.INFORMATION_MESSAGE);
                            ok = false;
                        }
                    }
                    if(tfTantargy.getText().equals("") && dat != null){ //Ha üres a tantárgy mezője
                        JOptionPane.showMessageDialog(null, "Írja be a tanár tanított tárgyát!", "Nem megfelelő bemenet", JOptionPane.INFORMATION_MESSAGE);
                        ok = false;
                    }
                    else if(ok == true){ //Ha minden mező helyes
                        for(Tanar t: jMain.tanarok){
                            if(t.getNev().equals(nev) && t.getSzulEv().equals(datum)){
                                t.setNev(tfNev.getText());
                                t.setCim(tfCim.getText());
                                t.setSzulEv(dat);
                                t.setTargy(tfTantargy.getText());
                                JOptionPane.showMessageDialog(null, "Sikeres módosítás!", "Módosítás", JOptionPane.INFORMATION_MESSAGE);
                                jMain.cbInit();
                                this.dispose();
                            }
                        }
                    }
                }
                case "Diák" -> {
                    int azon = 0;
                    if(tfNev.getText().equals("")){ //Ha üres a név mezője
                        JOptionPane.showMessageDialog(null, "Írja be a diák nevét!", "Nem megfelelő bemenet", JOptionPane.INFORMATION_MESSAGE);
                        ok = false;
                    }
                    else if(tfCim.getText().equals("")){ //Ha üres a cím mezője
                        JOptionPane.showMessageDialog(null, "Írja be a diák címét!", "Nem megfelelő bemenet", JOptionPane.INFORMATION_MESSAGE);
                        ok = false;
                    }
                    else if(tfDatum.getText().equals("")){ //Ha üres a dátum mezője
                        JOptionPane.showMessageDialog(null, "Írja be a diák születési dátumát!", "Nem megfelelő bemenet", JOptionPane.INFORMATION_MESSAGE);
                        ok = false;
                    }
                    else if(!tfDatum.getText().equals("")){ //Ha nem megfelelő a dátum formátuma
                        try{
                            dat = LocalDate.parse(tfDatum.getText());
                        }
                        catch(Exception ex){
                            JOptionPane.showMessageDialog(null, "Nem megfelelő formátum!\nHelyes formátum: ÉÉÉÉ-HH-NN", "Nem megfelelő bemenet", JOptionPane.INFORMATION_MESSAGE);
                            ok = false;
                        }
                    }
                    if(tfOsztaly.getText().equals("") && dat != null){ //Ha üres az osztály mezője
                        JOptionPane.showMessageDialog(null, "Írja be a diák osztályát!", "Nem megfelelő bemenet", JOptionPane.INFORMATION_MESSAGE);
                        ok = false;
                    }
                    else if(tfAzon.getText().equals("") || tfAzon.getText().length() != 8){ //Ha üres az azonosító mezője vagy nem megfelelő hosszúságú
                        JOptionPane.showMessageDialog(null, "Írja be a diák azonosítóját!", "Nem megfelelő bemenet", JOptionPane.INFORMATION_MESSAGE);
                        ok = false;
                    }
                    else if(!tfAzon.getText().equals("")){ //Ha nem szám formátumú az azonosító mezőjébe írt adat
                        try{
                            azon = Integer.parseInt(tfAzon.getText());
                        }
                        catch(NumberFormatException ex){
                            JOptionPane.showMessageDialog(null, "Nem megfelelő formátum!\nHelyes formátum: 8 számjegyű számsor", "Nem megfelelő bemenet", JOptionPane.INFORMATION_MESSAGE);
                            ok = false;
                        }
                    }
                    if(ok == true){ //Ha minden mező megfelelő
                        for(Diak d: jMain.diakok){
                            if(d.getNev().equals(nev) && d.getSzulEv().equals(datum)){
                                d.setNev(tfNev.getText());
                                d.setCim(tfCim.getText());
                                d.setSzulEv(dat);
                                d.setOsztaly(tfOsztaly.getText());
                                d.setAzon(azon);
                                JOptionPane.showMessageDialog(null, "Sikeres módosítás!", "Módosítás", JOptionPane.INFORMATION_MESSAGE);
                                jMain.cbInit();
                                this.dispose();
                            }
                        }
                    }
                }
                case "Intézmény" -> {
                    if(tfNev.getText().equals("")){ //Ha üres a név mezője
                        JOptionPane.showMessageDialog(null, "Írja be az intézmény nevét!", "Nem megfelelő bemenet", JOptionPane.INFORMATION_MESSAGE);
                        ok = false;
                    }
                    else if(tfCim.getText().equals("")){ //Ha üres a cím mezője
                        JOptionPane.showMessageDialog(null, "Írja be az intézmény címét!", "Nem megfelelő bemenet", JOptionPane.INFORMATION_MESSAGE);
                        ok = false;
                    }
                    else if(tfIntVez.getText().equals("")){ //Ha üres az intézmény vezető nevének a mezője
                        JOptionPane.showMessageDialog(null, "Írja be az intézmény vezetőjének/vezetőinek nevét/neveit!", "Nem megfelelő bemenet", JOptionPane.INFORMATION_MESSAGE);
                        ok = false;
                    }
                    else if(ok == true){ //Ha minden mező megfelelő
                        for(Intezmeny i: jMain.intezmenyek){
                            if(i.getNev().equals(nev) && i.getCim().equals(cim)){
                                i.setNev(tfNev.getText());
                                i.setCim(tfCim.getText());
                                i.setIntezmenyVezeto(tfIntVez.getText());
                                JOptionPane.showMessageDialog(null, "Sikeres módosítás!", "Módosítás", JOptionPane.INFORMATION_MESSAGE);
                                jMain.cbInit();
                                this.dispose();
                            }
                        }
                    }
                }
                default -> {
                }
            }
        }
    }//GEN-LAST:event_btnModActionPerformed

    /**
     * Main függvény
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jModosit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jModosit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jModosit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jModosit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jModosit(sor, tm, sel).setVisible(true);
            }
        });
    }

    /**
     * A táblázatban kiválasztott sor adatainak a megfelelő mezőkbe való feltöltése
     */
    private void initTb() {
        switch (sel) {
            case "Tanár" -> {
                tfNev.setText(tm.getValueAt(sor, 0).toString());
                tfCim.setText(tm.getValueAt(sor, 1).toString());
                tfDatum.setText(tm.getValueAt(sor, 2).toString());
                tfTantargy.setText(tm.getValueAt(sor, 3).toString());
                tfNev.setEnabled(true);
                tfCim.setEnabled(true);
                tfDatum.setEnabled(true);
                tfTantargy.setEnabled(true);
                tfAzon.setEnabled(false);
                tfOsztaly.setEnabled(false);
                tfIntVez.setEnabled(false);
            }
            case "Diák" -> {
                tfNev.setText(tm.getValueAt(sor, 0).toString());
                tfCim.setText(tm.getValueAt(sor, 1).toString());
                tfDatum.setText(tm.getValueAt(sor, 2).toString());
                tfOsztaly.setText(tm.getValueAt(sor, 3).toString());
                tfAzon.setText(tm.getValueAt(sor, 4).toString());
                tfNev.setEnabled(true);
                tfCim.setEnabled(true);
                tfDatum.setEnabled(true);
                tfTantargy.setEnabled(false);
                tfAzon.setEnabled(true);
                tfOsztaly.setEnabled(true);
                tfIntVez.setEnabled(false);
            }
            case "Intézmény" -> {
                tfNev.setText(tm.getValueAt(sor, 0).toString());
                tfCim.setText(tm.getValueAt(sor, 1).toString());
                tfIntVez.setText(tm.getValueAt(sor, 2).toString());
                tfNev.setEnabled(true);
                tfCim.setEnabled(true);
                tfDatum.setEnabled(false);
                tfTantargy.setEnabled(false);
                tfAzon.setEnabled(false);
                tfOsztaly.setEnabled(false);
                tfIntVez.setEnabled(true);
            }
            default -> {}
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMegse;
    private javax.swing.JButton btnMod;
    private javax.swing.JLabel lblAzon;
    private javax.swing.JLabel lblCim;
    private javax.swing.JLabel lblDatum;
    private javax.swing.JLabel lblIntVez;
    private javax.swing.JLabel lblNev;
    private javax.swing.JLabel lblOsztaly;
    private javax.swing.JLabel lblTantargy;
    private javax.swing.JTextField tfAzon;
    private javax.swing.JTextField tfCim;
    private javax.swing.JTextField tfDatum;
    private javax.swing.JTextField tfIntVez;
    private javax.swing.JTextField tfNev;
    private javax.swing.JTextField tfOsztaly;
    private javax.swing.JTextField tfTantargy;
    // End of variables declaration//GEN-END:variables

}
